# مقادیر ویژه و بردار ویژه


In [6]:
import numpy as np

In [14]:
A = np.array([[1, 4], [3, 2]])
print(A)

[[1 4]
 [3 2]]


In [15]:
L, V =np.linalg.eig(A)

# مقادیر ویژه

In [16]:
print(L)

[-2.  5.]


# بردار ویژه

In [17]:
print(V)

[[-0.8        -0.70710678]
 [ 0.6        -0.70710678]]


In [18]:
B = np.array([[1, 2, 30], [0, 3, 0], [0, 0, 1]])
print(B)

[[ 1  2 30]
 [ 0  3  0]
 [ 0  0  1]]


In [19]:
L, V =  np.linalg.eig(B)

In [ ]:
print(L)

[1. 3. 1.]


In [23]:
print(np.around(V, decimals=2))

[[ 1.    0.71 -1.  ]
 [ 0.    0.71  0.  ]
 [ 0.    0.    0.  ]]


In [25]:
import sympy as sp

In [27]:
B = sp.Matrix([[1, 2, 30], [0, 3, 0], [0, 0, 1]])
B

Matrix([
[1, 2, 30],
[0, 3,  0],
[0, 0,  1]])

# مقدار ویژه

In [29]:
B.eigenvals()

{3: 1, 1: 2}

# بردار ویژه

In [30]:
B.eigenvects()

[(1,
  2,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1],
   [0]])])]