In [15]:
import numpy as np

In [16]:
a = np.array([[6, 4, 24], [1, -9, 8]])
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [17]:
type(a)

numpy.ndarray

دو سطر ، سه ستون

In [18]:
a.shape

(2, 3)

تعداد اعضا

In [19]:
a.size

6

سطر اول

In [20]:
a[0]

array([ 6,  4, 24])

سطر دوم

In [21]:
a[1]

array([ 1, -9,  8])

سطون اول

In [ ]:
a[:, 0]

array([6, 1])

سطون دوم

In [24]:
a[:, 1]

array([ 4, -9])

سطر سوم

In [25]:
a[:, 2]

array([24,  8])

عضو اول (سطر اول ستون اول)

In [26]:
a[0][0]

6

In [30]:
a[:1]

array([[ 6,  4, 24]])

In [27]:
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
b[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b[0:2, :1]

array([[1],
       [4]])

In [37]:
c = np.array([[1, 2], [3, 4]])
print(c)

[[1 2]
 [3 4]]


In [35]:
c.sum()

10

جمع اعداد داخل یک ستون

In [38]:
c.sum(axis=0)

array([4, 6])

حمع اعداد داخل یک سطر

In [39]:
c.sum(axis=1)

array([3, 7])

In [42]:
d = c * 2
d

array([[2, 4],
       [6, 8]])

In [44]:
a = np.array([[4, 5], [2, 0]])
b = np.array([[4, 6], [7, 1]])
print(a)
print(b)

[[4 5]
 [2 0]]
[[4 6]
 [7 1]]


In [45]:
a + b

array([[ 8, 11],
       [ 9,  1]])

In [46]:
a - b

array([[ 0, -1],
       [-5, -1]])

ضرب خارجی

In [47]:
a * b

array([[16, 30],
       [14,  0]])

ضرب داخلی

In [48]:
np.dot(a, b)

array([[51, 29],
       [ 8, 12]])

In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [52]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

ماتریس متقارن

In [54]:
a = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
a == a.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

جمع عناضر روی قطر اصلی

In [56]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
np.trace(a)

15

دترمینان ماتریس

In [59]:
x = np.array([[8, 3],[4, 2]])
print(x)

[[8 3]
 [4 2]]


In [60]:
np.linalg.det(x)

3.999999999999999

In [62]:
y = np.array([[1, 2, 3], [3, 1 ,2],[0, 0, 1]])
print(y)

[[1 2 3]
 [3 1 2]
 [0 0 1]]


In [63]:
np.linalg.det(y)

-5.000000000000001

In [65]:
z = np.array([[5, 0, 0], [0, 4 ,0],[0, 0, 2]])
print(z)

[[5 0 0]
 [0 4 0]
 [0 0 2]]


In [66]:
np.linalg.det(z)

40.0

وارون یک ماتریس

In [67]:
a = np.array([[4, 3], [3, 2]])
a

array([[4, 3],
       [3, 2]])

In [68]:
np.linalg.inv(a)

array([[-2.,  3.],
       [ 3., -4.]])

In [70]:
b = np.array([[1, 2, 3],[0, 1, 4], [5, 6, 0]])
print(b)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [71]:
np.linalg.inv(b)

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

نورم ماتریس

In [73]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [74]:
np.linalg.norm(a)

5.477225575051661

یا

In [78]:
np.sqrt(np.trace(a.dot(a.T)))

5.477225575051661

In [79]:
import sympy as sp

In [80]:
a = sp.Matrix([[-6, 3], [4, 5]])
a

Matrix([
[-6, 3],
[ 4, 5]])

In [81]:
a.row(0)

Matrix([[-6, 3]])

In [82]:
a.col(0)

Matrix([
[-6],
[ 4]])

In [83]:
a.shape

(2, 2)

In [86]:
a.inv()

Matrix([
[-5/42, 1/14],
[ 2/21,  1/7]])

In [87]:
a.det()

-42

ماتریس صفر

In [90]:
sp.zeros(5, 4)

Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

ماتریس همانی

In [89]:
sp.eye(5)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

ماتریس قطری

In [91]:
sp.diag(1, 2, 3, 4)

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0],
[0, 0, 0, 4]])