# تجزیه ماتریس

In [1]:
import numpy as np

In [4]:
A = np.array([[3, 1, 1],
              [-1, 3, 1]])
print(A)

[[ 3  1  1]
 [-1  3  1]]


In [6]:
AT = A.T
print(AT)

[[ 3 -1]
 [ 1  3]
 [ 1  1]]


In [7]:
np.dot(A, AT)

array([[11,  1],
       [ 1, 11]])

In [8]:
np.dot(AT, A)

array([[10,  0,  2],
       [ 0, 10,  4],
       [ 2,  4,  2]])

In [9]:
U, s, Vt = np.linalg.svd(A)